package com.oandmdigital.radioplayer.ui;

import android.content.Intent;
import android.support.v7.app.AppCompatActivity;
import android.os.Bundle;

import com.oandmdigital.radioplayer.event.CategoryOnClickEvent;

import de.greenrobot.event.EventBus;

public class CategoryActivity extends AppCompatActivity {

    // added 'SingleTop' launch mode - stops the activity being destroyed
    // and recreated with the fragment when navigating back to it using
    // the 'Up arrow' from the child activity, eg StationActivity
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);

        // load the fragment into th default container
        if(getFragmentManager().findFragmentById(android.R.id.content) == null) {
            getFragmentManager().beginTransaction()
                    .add(android.R.id.content, CategoryFragment.newInstance())
                    .commit();
        }
    }


    @Override
    protected void onResume() {
        super.onResume();
        EventBus.getDefault().register(this);
    }


    @Override
    protected void onPause() {
        EventBus.getDefault().unregister(this);
        super.onPause();
    }


    // handles the onClick event generated by clicking on a category list item
    @SuppressWarnings("unused")
    public void onEventMainThread(CategoryOnClickEvent event) {
        // fetch the category object corresponding to the list item clicked
        // bundle it into an intent and launch the Station activity
        Intent intent = new Intent(this, StationActivity.class);
        intent.putExtra(StationFragment.CATEGORY_PARCELABLE, event.getCategory());
        startActivity(intent);
    }

}
